//  GenerationStore.swift
//  State + history for the 创作 (image/video) panels. Mirrors ChatStore's async
//  task + @Published pattern and DictationHistoryStore's file persistence: the
//  generated bytes are archived under Application Support/generations/, and a
//  lightweight index (generations.json) records prompt/model/file per item. Cost
//  is recorded to the shared UsageStore (source "image"/"video").

import Foundation
import Combine

/// One finished generation (an image now; video in Phase B).
struct GeneratedItem: Identifiable, Codable, Hashable {
    var id: String
    var date: Date
    var kind: String          // "image" / "video"
    var prompt: String
    var modelLabel: String    // 渠道商/模型ID at generation time
    var fileName: String      // relative to the generations directory
    var revisedPrompt: String?

    var fileURL: URL { GenerationStore.directory.appendingPathComponent(fileName) }
}

@MainActor
final class GenerationStore: ObservableObject {
    @Published private(set) var items: [GeneratedItem] = []
    @Published var isGenerating = false
    @Published var lastError: String?
    /// Live status for the long-running video job ("生成中…", progress 0-1).
    @Published var videoStatus: String?
    @Published var videoProgress: Double?

    private let settings: SettingsStore
    private let usage: UsageStore
    private var task: Task<Void, Never>?

    nonisolated static var directory: URL {
        SettingsStore.configDirectory().appendingPathComponent("generations", isDirectory: true)
    }
    private var indexURL: URL {
        SettingsStore.configDirectory().appendingPathComponent("generations.json")
    }
    private var saveWorkItem: DispatchWorkItem?

    init(settings: SettingsStore, usage: UsageStore) {
        self.settings = settings
        self.usage = usage
        try? FileManager.default.createDirectory(at: Self.directory, withIntermediateDirectories: true)
        load()
    }

    func items(kind: String) -> [GeneratedItem] { items.filter { $0.kind == kind } }

    // MARK: - Image generation

    /// Awaitable core: generate, archive, record usage, return the new items.
    /// Used by both the 创作 panel and the chat `generate_image` skill so a
    /// model-triggered generation lands in the same history/cost pipeline.
    func generateImageNow(model: ModelConfig, prompt: String, params: [String: String]) async throws -> [GeneratedItem] {
        let trimmed = prompt.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { throw OrbitError("提示词为空。") }
        guard let resolved = settings.settings.resolve(model) else {
            throw OrbitError("无法解析所选图像模型。")
        }
        let label = settings.settings.displayLabel(for: model)
        let assets = try await ImageClient.generate(resolved, prompt: trimmed, params: params)
        var newItems: [GeneratedItem] = []
        for asset in assets {
            let id = UUID().uuidString
            let name = "\(id).\(asset.ext)"
            try? asset.data.write(to: Self.directory.appendingPathComponent(name), options: .atomic)
            newItems.append(GeneratedItem(
                id: id, date: Date(), kind: "image", prompt: trimmed,
                modelLabel: label, fileName: name, revisedPrompt: asset.revisedPrompt))
        }
        items.insert(contentsOf: newItems, at: 0)
        // Per-call cost (image is billed per request; token usage n/a).
        usage.add(settings.settings.usageRecord(for: model, source: "image", date: Date()))
        save()
        return newItems
    }

    /// Fire-and-forget wrapper driving the panel's @Published state.
    func generateImage(model: ModelConfig, prompt: String, params: [String: String]) {
        guard !isGenerating else { return }
        isGenerating = true
        lastError = nil
        task = Task { [weak self] in
            guard let self else { return }
            do {
                _ = try await self.generateImageNow(model: model, prompt: prompt, params: params)
            } catch {
                if !Task.isCancelled && !(error is CancellationError) {
                    self.lastError = error.localizedDescription
                }
            }
            self.isGenerating = false
            self.task = nil
        }
    }

    // MARK: - Video generation (async submit → poll → download)

    /// Awaitable core, shared by the 创作 panel and the `generate_video` skill.
    func generateVideoNow(model: ModelConfig, prompt: String, params: [String: String]) async throws -> GeneratedItem {
        let trimmed = prompt.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { throw OrbitError("提示词为空。") }
        guard let resolved = settings.settings.resolve(model) else {
            throw OrbitError("无法解析所选视频模型。")
        }
        let label = settings.settings.displayLabel(for: model)
        let asset = try await VideoClient.generate(resolved, prompt: trimmed, params: params) { [weak self] status, progress in
            self?.videoStatus = status
            self?.videoProgress = progress
        }
        let id = UUID().uuidString
        let name = "\(id).\(asset.ext)"
        try? asset.data.write(to: Self.directory.appendingPathComponent(name), options: .atomic)
        let item = GeneratedItem(id: id, date: Date(), kind: "video", prompt: trimmed,
                                 modelLabel: label, fileName: name, revisedPrompt: nil)
        items.insert(item, at: 0)
        usage.add(settings.settings.usageRecord(for: model, source: "video", date: Date()))
        save()
        return item
    }

    /// Fire-and-forget wrapper driving the panel's @Published state.
    func generateVideo(model: ModelConfig, prompt: String, params: [String: String]) {
        guard !isGenerating else { return }
        isGenerating = true
        lastError = nil
        videoStatus = "准备中…"
        videoProgress = nil
        task = Task { [weak self] in
            guard let self else { return }
            do {
                _ = try await self.generateVideoNow(model: model, prompt: prompt, params: params)
            } catch {
                if !Task.isCancelled && !(error is CancellationError) {
                    self.lastError = error.localizedDescription
                }
            }
            self.isGenerating = false
            self.videoStatus = nil
            self.videoProgress = nil
            self.task = nil
        }
    }

    func cancel() {
        task?.cancel()
        task = nil
        isGenerating = false
        videoStatus = nil
        videoProgress = nil
    }

    func remove(id: String) {
        if let item = items.first(where: { $0.id == id }) {
            try? FileManager.default.removeItem(at: item.fileURL)
        }
        items.removeAll { $0.id == id }
        save()
    }

    // MARK: - Persistence

    private func load() {
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        guard let data = try? Data(contentsOf: indexURL),
              let decoded = try? decoder.decode([GeneratedItem].self, from: data) else { return }
        items = decoded
    }

    private func save() {
        saveWorkItem?.cancel()
        let snapshot = items
        let url = indexURL
        let item = DispatchWorkItem {
            let encoder = JSONEncoder()
            encoder.dateEncodingStrategy = .iso8601
            encoder.outputFormatting = [.prettyPrinted]
            guard let data = try? encoder.encode(snapshot) else { return }
            try? data.write(to: url, options: .atomic)
        }
        saveWorkItem = item
        DispatchQueue.global(qos: .utility).asyncAfter(deadline: .now() + 0.5, execute: item)
    }
}
