//! Codex App Server V2 wire types.
//!
//! The schemas are generated by OpenAI Codex `rust-v0.145.0` from
//! `codex-rs/app-server-protocol` and retained under Apache-2.0. Tietiezhi
//! generates Rust types from those pinned schemas at compile time instead of
//! linking to or invoking the Codex executable.

#![allow(clippy::large_enum_variant)]

pub const CODEX_VERSION: &str = "0.145.0";
pub const CODEX_TAG: &str = "rust-v0.145.0";
pub const CODEX_COMMIT: &str = "25af12f7e61572b0bc18ddb1008be543b91519b0";

mod generated_v2 {
    typify::import_types!(
        schema = "../../shared/codex/v2/schema/codex_app_server_protocol.v2.schemas.json",
        derives = [schemars::JsonSchema],
    );
}

pub use generated_v2::*;

pub mod client_notification {
    typify::import_types!(
        schema = "../../shared/codex/v2/schema/ClientNotification.json",
        derives = [schemars::JsonSchema],
    );
}

pub mod server_request {
    use schemars::JsonSchema;
    use serde::{Deserialize, Serialize};

    macro_rules! import_params {
        ($module:ident, $schema:literal) => {
            pub mod $module {
                typify::import_types!(schema = $schema, derives = [schemars::JsonSchema],);
            }
        };
    }

    import_params!(
        command_execution,
        "../../shared/codex/v2/schema/CommandExecutionRequestApprovalParams.json"
    );
    import_params!(
        file_change,
        "../../shared/codex/v2/schema/FileChangeRequestApprovalParams.json"
    );
    import_params!(
        tool_user_input,
        "../../shared/codex/v2/schema/ToolRequestUserInputParams.json"
    );
    import_params!(
        permissions,
        "../../shared/codex/v2/schema/PermissionsRequestApprovalParams.json"
    );
    import_params!(
        dynamic_tool,
        "../../shared/codex/v2/schema/DynamicToolCallParams.json"
    );
    import_params!(
        auth_refresh,
        "../../shared/codex/v2/schema/ChatgptAuthTokensRefreshParams.json"
    );
    import_params!(
        attestation,
        "../../shared/codex/v2/schema/AttestationGenerateParams.json"
    );
    import_params!(
        apply_patch,
        "../../shared/codex/v2/schema/ApplyPatchApprovalParams.json"
    );
    import_params!(
        exec_command,
        "../../shared/codex/v2/schema/ExecCommandApprovalParams.json"
    );

    pub mod mcp_schema {
        typify::import_types!(
            schema = "../../shared/codex/v2/compat-schema/McpElicitationSchema.json",
            derives = [schemars::JsonSchema],
        );
    }

    pub use apply_patch::ApplyPatchApprovalParams;
    pub use attestation::AttestationGenerateParams;
    pub use auth_refresh::ChatgptAuthTokensRefreshParams;
    pub use command_execution::CommandExecutionRequestApprovalParams;
    pub use dynamic_tool::DynamicToolCallParams;
    pub use exec_command::ExecCommandApprovalParams;
    pub use file_change::FileChangeRequestApprovalParams;
    pub use mcp_schema::McpElicitationSchema;
    pub use permissions::PermissionsRequestApprovalParams;
    pub use tool_user_input::ToolRequestUserInputParams;

    #[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
    #[serde(rename_all = "camelCase")]
    pub struct McpServerElicitationRequestParams {
        pub thread_id: String,
        pub turn_id: Option<String>,
        pub server_name: String,
        #[serde(flatten)]
        pub request: McpElicitationRequest,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
    #[serde(tag = "mode", rename_all_fields = "camelCase")]
    pub enum McpElicitationRequest {
        #[serde(rename = "form")]
        Form {
            #[serde(rename = "_meta")]
            meta: Option<serde_json::Value>,
            message: String,
            requested_schema: McpElicitationSchema,
        },
        #[serde(rename = "openai/form")]
        OpenAiForm {
            #[serde(rename = "_meta")]
            meta: Option<serde_json::Value>,
            message: String,
            requested_schema: serde_json::Value,
        },
        #[serde(rename = "url")]
        Url {
            #[serde(rename = "_meta")]
            meta: Option<serde_json::Value>,
            message: String,
            url: String,
            elicitation_id: String,
        },
    }

    #[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
    #[serde(tag = "method")]
    pub enum ServerRequest {
        #[serde(rename = "item/commandExecution/requestApproval")]
        CommandExecutionRequestApproval {
            id: crate::RequestId,
            params: CommandExecutionRequestApprovalParams,
        },
        #[serde(rename = "item/fileChange/requestApproval")]
        FileChangeRequestApproval {
            id: crate::RequestId,
            params: FileChangeRequestApprovalParams,
        },
        #[serde(rename = "item/tool/requestUserInput")]
        ToolRequestUserInput {
            id: crate::RequestId,
            params: ToolRequestUserInputParams,
        },
        #[serde(rename = "mcpServer/elicitation/request")]
        McpServerElicitationRequest {
            id: crate::RequestId,
            params: McpServerElicitationRequestParams,
        },
        #[serde(rename = "item/permissions/requestApproval")]
        PermissionsRequestApproval {
            id: crate::RequestId,
            params: PermissionsRequestApprovalParams,
        },
        #[serde(rename = "item/tool/call")]
        DynamicToolCall {
            id: crate::RequestId,
            params: DynamicToolCallParams,
        },
        #[serde(rename = "account/chatgptAuthTokens/refresh")]
        ChatgptAuthTokensRefresh {
            id: crate::RequestId,
            params: ChatgptAuthTokensRefreshParams,
        },
        #[serde(rename = "attestation/generate")]
        AttestationGenerate {
            id: crate::RequestId,
            params: AttestationGenerateParams,
        },
        #[serde(rename = "applyPatchApproval")]
        ApplyPatchApproval {
            id: crate::RequestId,
            params: ApplyPatchApprovalParams,
        },
        #[serde(rename = "execCommandApproval")]
        ExecCommandApproval {
            id: crate::RequestId,
            params: ExecCommandApprovalParams,
        },
    }

    impl ServerRequest {
        pub fn id(&self) -> &crate::RequestId {
            match self {
                Self::CommandExecutionRequestApproval { id, .. }
                | Self::FileChangeRequestApproval { id, .. }
                | Self::ToolRequestUserInput { id, .. }
                | Self::McpServerElicitationRequest { id, .. }
                | Self::PermissionsRequestApproval { id, .. }
                | Self::DynamicToolCall { id, .. }
                | Self::ChatgptAuthTokensRefresh { id, .. }
                | Self::AttestationGenerate { id, .. }
                | Self::ApplyPatchApproval { id, .. }
                | Self::ExecCommandApproval { id, .. } => id,
            }
        }

        pub fn method(&self) -> &'static str {
            match self {
                Self::CommandExecutionRequestApproval { .. } => {
                    "item/commandExecution/requestApproval"
                }
                Self::FileChangeRequestApproval { .. } => "item/fileChange/requestApproval",
                Self::ToolRequestUserInput { .. } => "item/tool/requestUserInput",
                Self::McpServerElicitationRequest { .. } => "mcpServer/elicitation/request",
                Self::PermissionsRequestApproval { .. } => "item/permissions/requestApproval",
                Self::DynamicToolCall { .. } => "item/tool/call",
                Self::ChatgptAuthTokensRefresh { .. } => "account/chatgptAuthTokens/refresh",
                Self::AttestationGenerate { .. } => "attestation/generate",
                Self::ApplyPatchApproval { .. } => "applyPatchApproval",
                Self::ExecCommandApproval { .. } => "execCommandApproval",
            }
        }
    }
}

/// Adapted from Codex `codex-rs/app-server-protocol/src/rpc.rs` at
/// `rust-v0.145.0`; the trace context is represented by a local wire-equivalent
/// struct so this crate remains independent from Codex internals.
pub mod rpc {
    use crate::RequestId;
    use schemars::JsonSchema;
    use serde::{Deserialize, Serialize};

    pub const JSONRPC_VERSION: &str = "2.0";

    #[derive(Debug, Clone, Deserialize, Serialize, JsonSchema)]
    #[serde(untagged)]
    pub enum JSONRPCMessage {
        Request(JSONRPCRequest),
        Notification(JSONRPCNotification),
        Response(JSONRPCResponse),
        Error(JSONRPCError),
    }

    #[derive(Debug, Clone, Deserialize, Serialize, JsonSchema)]
    #[serde(rename_all = "camelCase")]
    pub struct W3cTraceContext {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub traceparent: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub tracestate: Option<String>,
    }

    #[derive(Debug, Clone, Deserialize, Serialize, JsonSchema)]
    pub struct JSONRPCRequest {
        pub id: RequestId,
        pub method: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub params: Option<serde_json::Value>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub trace: Option<W3cTraceContext>,
    }

    #[derive(Debug, Clone, Deserialize, Serialize, JsonSchema)]
    pub struct JSONRPCNotification {
        pub method: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub params: Option<serde_json::Value>,
    }

    #[derive(Debug, Clone, Deserialize, Serialize, JsonSchema)]
    pub struct JSONRPCResponse {
        pub id: RequestId,
        pub result: serde_json::Value,
    }

    #[derive(Debug, Clone, Deserialize, Serialize, JsonSchema)]
    pub struct JSONRPCError {
        pub error: JSONRPCErrorError,
        pub id: RequestId,
    }

    #[derive(Debug, Clone, Deserialize, Serialize, JsonSchema)]
    pub struct JSONRPCErrorError {
        pub code: i64,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub data: Option<serde_json::Value>,
        pub message: String,
    }
}

pub use client_notification::ClientNotification;
pub use rpc::{
    JSONRPCError, JSONRPCErrorError, JSONRPCMessage, JSONRPCNotification, JSONRPCRequest,
    JSONRPCResponse,
};
pub use server_request::ServerRequest;

pub fn canonical_v2_schema() -> serde_json::Value {
    serde_json::from_str(include_str!(
        "../../../shared/codex/v2/schema/codex_app_server_protocol.v2.schemas.json"
    ))
    .expect("pinned Codex V2 schema must be valid JSON")
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde::Serialize;
    use serde::de::DeserializeOwned;
    use serde_json::Value;

    fn assert_roundtrip<T>(fixture: &str)
    where
        T: DeserializeOwned + Serialize,
    {
        let expected: Value = serde_json::from_str(fixture).unwrap();
        let decoded: T = serde_json::from_value(expected.clone()).unwrap();
        let actual = serde_json::to_value(decoded).unwrap();
        assert_eq!(actual, expected);
    }

    #[test]
    fn pinned_schema_contains_all_v2_surface_types() {
        let schema = canonical_v2_schema();
        let definitions = schema["definitions"].as_object().unwrap();
        assert_eq!(
            definitions["ClientRequest"]["oneOf"]
                .as_array()
                .unwrap()
                .len(),
            89
        );
        assert_eq!(
            definitions["ServerNotification"]["oneOf"]
                .as_array()
                .unwrap()
                .len(),
            70
        );
        assert!(definitions.len() >= 532);
    }

    #[test]
    fn rust_schema_generation_preserves_wire_method_counts() {
        fn variants(schema: &Value) -> &Vec<Value> {
            schema["oneOf"]
                .as_array()
                .or_else(|| schema["anyOf"].as_array())
                .unwrap()
        }

        let client = serde_json::to_value(schemars::schema_for!(ClientRequest)).unwrap();
        let notifications =
            serde_json::to_value(schemars::schema_for!(ServerNotification)).unwrap();
        let requests = serde_json::to_value(schemars::schema_for!(ServerRequest)).unwrap();
        assert_eq!(variants(&client).len(), 89);
        assert_eq!(variants(&notifications).len(), 70);
        assert_eq!(variants(&requests).len(), 10);
    }

    #[test]
    fn official_wire_fixtures_roundtrip() {
        assert_roundtrip::<ClientRequest>(include_str!(
            "../../../shared/codex/v2/fixtures/client-request-thread-list.json"
        ));
        assert_roundtrip::<ClientNotification>(include_str!(
            "../../../shared/codex/v2/fixtures/client-notification-initialized.json"
        ));
        assert_roundtrip::<ServerRequest>(include_str!(
            "../../../shared/codex/v2/fixtures/server-request-command-approval.json"
        ));
        assert_roundtrip::<ServerRequest>(include_str!(
            "../../../shared/codex/v2/fixtures/server-request-mcp-elicitation.json"
        ));
        assert_roundtrip::<ServerNotification>(include_str!(
            "../../../shared/codex/v2/fixtures/server-notification-mcp-status.json"
        ));
        assert_roundtrip::<JSONRPCResponse>(include_str!(
            "../../../shared/codex/v2/fixtures/jsonrpc-response.json"
        ));
    }
}
